name: Build Fabric Mod from ZIP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Unzip project
        run: unzip aggressivity-changer.zip -d project

      - name: List files after unzip
        run: ls -R ./project

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./project/gradlew

      - name: Build Mod with Gradle
        run: ./project/gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: aggressivity-changer-jar
          path: ./project/build/libs/*.jar
