name: Build Mod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Unzip source
        run: unzip src.zip -d project

      - name: Debug list files
        run: ls -R ./project

      - name: Generate Gradle wrapper
        run: |
          cd project
          gradle wrapper

      - name: Make gradlew executable
        run: chmod +x ./project/gradlew

      - name: Build with Gradle
        run: ./project/gradlew build

      - name: List build output
        run: ls -R ./project

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-jar
          path: ./project/**/*.jar
